deployment:
  tasks:
    - export DEPLOYPATH=/home/smartuni/public_html/onroadmedia.in

    # Project copy
    - /bin/cp -R * $DEPLOYPATH

    # Laravel public folder fix
    - /bin/cp -R public/* $DEPLOYPATH

    # Go to project
    - cd $DEPLOYPATH

    # Install dependencies
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader

    # Laravel optimize
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan cache:clear